packages:
  - 'packages/core'
  - 'packages/cli'
  - 'packages/engines'
  - 'packages/renderers/*'
  - 'packages/features/core-markdown'
  - 'packages/features/main/*'
  - 'packages/features/containers/*'
  - 'packages/features/diagrams/*'
  - 'examples/*'
