import java.awt.*;
import java.awt.font.*;
import java.awt.geom.*;
import java.awt.image.BufferedImage;

/**
 * Extract exact glyph path coordinates and UnusedSpace centering offsets
 * for CircledCharacter letters (C, I, E, A) at Monospaced Bold 17pt.
 *
 * Matches Java PlantUML's complete rendering chain:
 *   CircledCharacter.drawU → DriverCenteredCharacterSvg → UnusedSpace → SvgGraphics.drawPathIterator
 *
 * Output: Rust constants for glyph path segments and centering offsets.
 * At render time: final_coord = path_coord + (circle_abs_pos - center_offset - 0.5)
 *
 * Usage:
 *   javac tests/tools/ExtractGlyphPaths.java -d tests/tools/
 *   java -cp tests/tools ExtractGlyphPaths
 */
public class ExtractGlyphPaths {

    // Exact copy of PlantUML's UnusedSpace algorithm (UnusedSpace.java)
    static double[] computeUnusedSpaceCenter(Font font, char c) {
        int HALF = 20;
        int SIZE = HALF * 2;
        BufferedImage im = new BufferedImage(SIZE, SIZE, BufferedImage.TYPE_INT_RGB);
        Graphics2D g = im.createGraphics();
        g.setRenderingHint(RenderingHints.KEY_TEXT_ANTIALIASING,
                           RenderingHints.VALUE_TEXT_ANTIALIAS_ON);
        g.setFont(font);
        g.drawString("" + c, HALF, HALF);
        g.dispose();

        int minI = SIZE, maxI = 0, minJ = SIZE, maxJ = 0;
        for (int j = 0; j < SIZE; j++) {
            for (int i = 0; i < SIZE; i++) {
                int rgb = im.getRGB(i, j) & 0xFFFFFF;
                if (rgb != 0) {
                    if (i < minI) minI = i;
                    if (i > maxI) maxI = i;
                    if (j < minJ) minJ = j;
                    if (j > maxJ) maxJ = j;
                }
            }
        }

        double bestDist = -1;
        int bestI = HALF, bestJ = HALF;
        for (int j = minJ * 4; j <= maxJ * 4; j++) {
            for (int i = minI * 4; i <= maxI * 4; i++) {
                double minDist = Double.MAX_VALUE;
                for (int j2 = minJ; j2 <= maxJ; j2++) {
                    for (int i2 = minI; i2 <= maxI; i2++) {
                        int rgb = im.getRGB(i2, j2) & 0xFFFFFF;
                        if (rgb != 0) {
                            double dx = i / 4.0 - i2;
                            double dy = j / 4.0 - j2;
                            double dist = Math.sqrt(dx * dx + dy * dy);
                            if (dist < minDist) minDist = dist;
                        }
                    }
                }
                if (minDist > bestDist) {
                    bestDist = minDist;
                    bestI = i;
                    bestJ = j;
                }
            }
        }

        return new double[]{ bestI / 4.0 - HALF, bestJ / 4.0 - HALF };
    }

    public static void main(String[] args) {
        Font font = new Font("Monospaced", Font.BOLD, 17);

        // Match PlantUML's SVG FontRenderContext
        BufferedImage img = new BufferedImage(10, 10, BufferedImage.TYPE_INT_RGB);
        Graphics2D g2d = img.createGraphics();
        g2d.setRenderingHint(RenderingHints.KEY_FRACTIONALMETRICS,
                             RenderingHints.VALUE_FRACTIONALMETRICS_ON);
        g2d.setRenderingHint(RenderingHints.KEY_TEXT_ANTIALIASING,
                             RenderingHints.VALUE_TEXT_ANTIALIAS_ON);
        FontRenderContext frc = g2d.getFontRenderContext();

        char[] chars = {'C', 'I', 'E', 'A'};

        System.out.println("// Auto-generated by ExtractGlyphPaths.java");
        System.out.println("// DO NOT EDIT. Regenerate with:");
        System.out.println("//   javac tests/tools/ExtractGlyphPaths.java -d tests/tools/");
        System.out.println("//   java -cp tests/tools ExtractGlyphPaths");
        System.out.println("//");
        System.out.println("// Glyph outlines from Java AWT TextLayout.getOutline()");
        System.out.println("// Font: Monospaced Bold 17pt (PlantUML FontParam.CIRCLED_CHARACTER)");
        System.out.println("// Centering: PlantUML UnusedSpace algorithm");
        System.out.println("//");
        System.out.println("// Usage: final_x = path_x + (circle_center_x - CENTER.0 - 0.5)");
        System.out.println("//        final_y = path_y + (circle_center_y - CENTER.1 - 0.5)");
        System.out.println();

        for (char c : chars) {
            double[] center = computeUnusedSpaceCenter(font, c);

            System.out.printf("pub const GLYPH_%c_CENTER: (f64, f64) = (%.17g, %.17g);%n",
                c, center[0], center[1]);

            // Get glyph outline via TextLayout (same as PlantUML)
            TextLayout tl = new TextLayout("" + c, font, frc);
            Shape outline = tl.getOutline(null);
            PathIterator pi = outline.getPathIterator(null);

            System.out.printf("pub const GLYPH_%c_PATH: &[(char, &[(f64, f64)])] = &[%n", c);
            double[] coords = new double[6];
            boolean first = true;
            while (!pi.isDone()) {
                int type = pi.currentSegment(coords);
                if (!first) System.out.println(",");
                first = false;

                switch (type) {
                    case PathIterator.SEG_MOVETO:
                        System.out.printf("    ('M', &[(%.17g, %.17g)])", coords[0], coords[1]);
                        break;
                    case PathIterator.SEG_LINETO:
                        System.out.printf("    ('L', &[(%.17g, %.17g)])", coords[0], coords[1]);
                        break;
                    case PathIterator.SEG_QUADTO:
                        System.out.printf("    ('Q', &[(%.17g, %.17g), (%.17g, %.17g)])",
                            coords[0], coords[1], coords[2], coords[3]);
                        break;
                    case PathIterator.SEG_CUBICTO:
                        System.out.printf("    ('C', &[(%.17g, %.17g), (%.17g, %.17g), (%.17g, %.17g)])",
                            coords[0], coords[1], coords[2], coords[3],
                            coords[4], coords[5]);
                        break;
                    case PathIterator.SEG_CLOSE:
                        System.out.print("    ('Z', &[])");
                        break;
                }
                pi.next();
            }
            System.out.println();
            System.out.println("];");
            System.out.println();
        }

        g2d.dispose();
    }
}
