#!/usr/bin/env python3
"""Regenerate `src/font_data.rs` from DejaVu TTF files.

Pre-extracts horizontal metrics + key vertical metrics from each TTF face
into compressed range tables, so the runtime only needs a small static
lookup (no ttf-parser dependency, no embedded TTFs in the binary).

The output of this script is byte-identical for a given input set —
re-running with the same fonts produces the same `src/font_data.rs`.

Usage:
    sudo apt install fonts-dejavu fonts-dejavu-extra fontconfig
    cp /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf \\
       /usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf \\
       /usr/share/fonts/truetype/dejavu/DejaVuSans-Oblique.ttf \\
       /usr/share/fonts/truetype/dejavu/DejaVuSans-BoldOblique.ttf \\
       /usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf \\
       /usr/share/fonts/truetype/dejavu/DejaVuSansMono-Bold.ttf \\
       /usr/share/fonts/truetype/dejavu/DejaVuSansMono-Oblique.ttf \\
       /usr/share/fonts/truetype/dejavu/DejaVuSansMono-BoldOblique.ttf \\
       /usr/share/fonts/truetype/dejavu/DejaVuSerif.ttf \\
       /usr/share/fonts/truetype/dejavu/DejaVuSerif-Bold.ttf \\
       /usr/share/fonts/truetype/dejavu/DejaVuSerif-Italic.ttf \\
       /usr/share/fonts/truetype/dejavu/DejaVuSerif-BoldItalic.ttf \\
       tools/fonts/
    pip install fonttools
    python3 tools/gen_font_data.py

`tools/fonts/*.ttf` is .gitignored — the TTFs are not vendored. Output
goes to `src/font_data.rs` (regenerate after any DejaVu upstream bump).
"""

import os
import sys

from fontTools.ttLib import TTFont

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FONTS_DIR = os.path.join(ROOT, "tools", "fonts")
OUTPUT = os.path.join(ROOT, "src", "font_data.rs")

# Pairs of (Rust static name, TTF filename under tools/fonts/).
FONTS = [
    ("DEJAVU_SANS",                "DejaVuSans.ttf"),
    ("DEJAVU_SANS_BOLD",           "DejaVuSans-Bold.ttf"),
    ("DEJAVU_SANS_OBLIQUE",        "DejaVuSans-Oblique.ttf"),
    ("DEJAVU_SANS_BOLD_OBLIQUE",   "DejaVuSans-BoldOblique.ttf"),
    ("DEJAVU_MONO",                "DejaVuSansMono.ttf"),
    ("DEJAVU_MONO_BOLD",           "DejaVuSansMono-Bold.ttf"),
    ("DEJAVU_MONO_OBLIQUE",        "DejaVuSansMono-Oblique.ttf"),
    ("DEJAVU_MONO_BOLD_OBLIQUE",   "DejaVuSansMono-BoldOblique.ttf"),
    ("DEJAVU_SERIF",               "DejaVuSerif.ttf"),
    ("DEJAVU_SERIF_BOLD",          "DejaVuSerif-Bold.ttf"),
    ("DEJAVU_SERIF_ITALIC",        "DejaVuSerif-Italic.ttf"),
    ("DEJAVU_SERIF_BOLD_ITALIC",   "DejaVuSerif-BoldItalic.ttf"),
]


def extract_font(path):
    font = TTFont(path)
    head = font["head"]
    hhea = font["hhea"]
    os2 = font["OS/2"]
    hmtx = font["hmtx"]

    cmap = font.getBestCmap()
    cp_to_advance = {cp: hmtx[g][0] for cp, g in cmap.items()}

    sorted_cps = sorted(cp_to_advance)
    ranges = []
    if sorted_cps:
        start = end = sorted_cps[0]
        adv = cp_to_advance[start]
        for cp in sorted_cps[1:]:
            cp_adv = cp_to_advance[cp]
            if cp == end + 1 and cp_adv == adv:
                end = cp
            else:
                ranges.append((start, end, adv))
                start = end = cp
                adv = cp_adv
        ranges.append((start, end, adv))

    info = {
        "units_per_em": head.unitsPerEm,
        "ascender": hhea.ascent,
        "descender": hhea.descent,
        "typo_ascender": os2.sTypoAscender,
        "ranges": ranges,
        "num_codepoints": len(sorted_cps),
    }
    font.close()
    return info


def render_rust(fonts_data):
    out = []
    out.append("//! Static font metric data extracted from DejaVu TTF files.")
    out.append("//!")
    out.append("//! Auto-generated by `tools/gen_font_data.py` — do not edit manually.")
    out.append("//!")
    out.append("//! Compressed range tables replace runtime TTF parsing, eliminating")
    out.append("//! both the embedded ~2.5 MB of TTF data and the ttf-parser dep.")
    out.append("")
    out.append("/// Metadata for a single font face.")
    out.append("#[derive(Debug, Clone, Copy)]")
    out.append("pub struct FontMeta {")
    out.append("    pub units_per_em: u16,")
    out.append("    pub ascender: i16,")
    out.append("    pub descender: i16,")
    out.append("    pub typo_ascender: i16,")
    out.append("    /// Range table: sorted by start codepoint, (start, end, advance).")
    out.append("    /// Binary search on `start` to find the range containing a codepoint.")
    out.append("    ranges: &'static [(u32, u32, u16)],")
    out.append("}")
    out.append("")
    out.append("impl FontMeta {")
    out.append("    /// Look up the horizontal advance for a Unicode codepoint.")
    out.append("    /// Returns `None` if the codepoint has no glyph in this font.")
    out.append("    #[inline]")
    out.append("    pub fn glyph_advance(&self, codepoint: u32) -> Option<u16> {")
    out.append("        let idx = self")
    out.append("            .ranges")
    out.append("            .partition_point(|&(start, _, _)| start <= codepoint);")
    out.append("        if idx == 0 {")
    out.append("            return None;")
    out.append("        }")
    out.append("        let (start, end, adv) = self.ranges[idx - 1];")
    out.append("        if codepoint >= start && codepoint <= end {")
    out.append("            Some(adv)")
    out.append("        } else {")
    out.append("            None")
    out.append("        }")
    out.append("    }")
    out.append("}")
    out.append("")

    for name, info in fonts_data:
        ranges = info["ranges"]
        out.append(f"pub static {name}: FontMeta = FontMeta {{")
        out.append(f"    units_per_em: {info['units_per_em']},")
        out.append(f"    ascender: {info['ascender']},")
        out.append(f"    descender: {info['descender']},")
        out.append(f"    typo_ascender: {info['typo_ascender']},")
        out.append(f"    ranges: &{name}_RANGES,")
        out.append("};")
        out.append("")
        out.append(f"/// {len(ranges)} ranges covering {info['num_codepoints']} codepoints.")
        out.append(f"static {name}_RANGES: [(u32, u32, u16); {len(ranges)}] = [")
        for start, end, adv in ranges:
            if start == end:
                out.append(f"    (0x{start:04X}, 0x{end:04X}, {adv}),    // U+{start:04X}")
            else:
                out.append(f"    (0x{start:04X}, 0x{end:04X}, {adv}),    // U+{start:04X}..U+{end:04X}")
        out.append("];")
        out.append("")

    return "\n".join(out)


def main():
    fonts_data = []
    for name, fname in FONTS:
        path = os.path.join(FONTS_DIR, fname)
        if not os.path.isfile(path):
            sys.stderr.write(f"missing TTF: {path}\n")
            sys.exit(1)
        info = extract_font(path)
        sys.stderr.write(
            f"{name:30s} upem={info['units_per_em']:5d} "
            f"asc={info['ascender']:5d} desc={info['descender']:5d} "
            f"typo_asc={info['typo_ascender']:5d} "
            f"cps={info['num_codepoints']:5d} ranges={len(info['ranges']):5d}\n"
        )
        fonts_data.append((name, info))

    rust_src = render_rust(fonts_data)
    with open(OUTPUT, "w", encoding="utf-8") as f:
        f.write(rust_src)
        f.write("\n")
    sys.stderr.write(f"\nwrote {OUTPUT}\n")


if __name__ == "__main__":
    main()
