#!/usr/bin/env python3
"""Generate reference_tests.rs from fixture files.

Scans tests/fixtures/ for .puml files and generates a Rust test file
with one test per fixture, using the reference_test! macro.

The actual SVG comparison logic lives in tests/support/svg_compare.rs;
this generator only emits a thin per-fixture macro. So regenerating
this file never loses the normalize_* / assert_exact_match helpers.

Usage:
    python3 tests/generate_test_list.py > tests/reference_tests.rs
"""

import os
import re

FIXTURES_DIR = os.path.join(os.path.dirname(__file__), "fixtures")
REFERENCE_INDEX = os.path.join(os.path.dirname(__file__), "reference", "INDEX.tsv")

PROLOGUE = '''#![allow(non_snake_case)]
// Auto-generated by tests/generate_test_list.py
// Do not edit manually. Regenerate with:
//   python3 tests/generate_test_list.py > tests/reference_tests.rs
//
// SVG comparison helpers live in tests/support/svg_compare.rs so this
// file stays a thin index of fixtures — regen cannot drop them.

use std::collections::HashMap;
use std::fs;
use std::path::Path;
use std::sync::OnceLock;

mod support;

use support::svg_compare::{assert_exact_match, assert_no_raw_markup};

fn convert_fixture(path: &str) -> String {
    static INIT: OnceLock<()> = OnceLock::new();
    INIT.get_or_init(|| {
        support::init_test_backend();
    });
    let source = fs::read_to_string(path).unwrap_or_else(|e| panic!("cannot read {path}: {e}"));
    plantuml_little::convert_with_input_path(&source, Path::new(path))
        .unwrap_or_else(|e| panic!("convert {path} failed: {e}"))
}

fn reference_index() -> &'static HashMap<String, String> {
    static INDEX: OnceLock<HashMap<String, String>> = OnceLock::new();
    INDEX.get_or_init(|| {
        let mut map = HashMap::new();
        let path = "tests/reference/INDEX.tsv";
        let content =
            fs::read_to_string(path).unwrap_or_else(|e| panic!("read {path} failed: {e}"));
        for (lineno, line) in content.lines().enumerate() {
            if line.trim().is_empty() {
                continue;
            }
            let (fixture, reference) = line
                .split_once('\\t')
                .unwrap_or_else(|| panic!("{path}: malformed line {}: {line}", lineno + 1));
            map.insert(format!("tests/{fixture}"), format!("tests/{reference}"));
        }
        map
    })
}

fn load_reference(fixture_path: &str) -> Option<String> {
    let direct_reference_path = fixture_path
        .replace("fixtures/", "reference/")
        .replace(".puml", ".svg");
    let reference_path = if Path::new(&direct_reference_path).exists() {
        direct_reference_path
    } else if let Some(mapped) = reference_index().get(fixture_path) {
        mapped.clone()
    } else {
        return None;
    };
    let bytes = fs::read(&reference_path)
        .unwrap_or_else(|e| panic!("read {reference_path} failed for {fixture_path}: {e}"));
    Some(String::from_utf8(bytes).unwrap_or_else(|e| {
        panic!("{fixture_path}: reference {reference_path} is not UTF-8 SVG: {e}")
    }))
}

macro_rules! reference_test {
    ($name:ident, $fixture:expr) => {
        #[test]
        fn $name() {
            let fixture = concat!("tests/", $fixture);
            let svg = convert_fixture(fixture);
            assert_no_raw_markup(&svg, fixture);
            // UPDATE_REF=1 cargo test reference -- to overwrite reference SVGs
            if std::env::var("UPDATE_REF").is_ok() {
                let ref_path = fixture
                    .replace("fixtures/", "reference/")
                    .replace(".puml", ".svg");
                fs::write(&ref_path, &svg).unwrap_or_else(|e| panic!("write {ref_path}: {e}"));
                return;
            }
            if let Some(reference) = load_reference(fixture) {
                assert_exact_match(&svg, &reference, fixture);
            }
        }
    };
}

'''


def sanitize_name(path: str) -> str:
    """Convert a fixture path to a valid Rust test function name."""
    name = path.replace("/", "_").replace("-", "_").replace(".", "_")
    if name and name[0].isdigit():
        name = "n" + name
    name = re.sub(r"[^a-zA-Z0-9_]", "_", name)
    name = re.sub(r"_+", "_", name).strip("_")
    return name


def main():
    fixtures = []
    for root, _dirs, files in os.walk(FIXTURES_DIR):
        for f in sorted(files):
            if not f.endswith(".puml"):
                continue
            full = os.path.join(root, f)
            rel = os.path.relpath(full, os.path.join(FIXTURES_DIR, ".."))
            fixtures.append(rel)
    fixtures.sort()

    print(PROLOGUE, end="")
    # Match what `cargo fmt` produces: rustfmt allows single-line macro
    # calls up to ~80 columns; longer ones get broken across lines.
    SINGLE_LINE_LIMIT = 78
    for rel in fixtures:
        name = sanitize_name(rel)
        ident = f"reference_{name}"
        single_line = f'reference_test!({ident}, "{rel}");'
        if len(single_line) <= SINGLE_LINE_LIMIT:
            print(single_line)
        else:
            print("reference_test!(")
            print(f"    {ident},")
            print(f'    "{rel}"')
            print(");")
    print()
    print(f"// Total: {len(fixtures)} reference tests")


if __name__ == "__main__":
    main()
