// Cross-language verification: Rust klimt output must match Java PlantUML exactly.
// Expected values from tests/fixtures/klimt_verify.json (generated by KlimtVerify.java)

use plantuml_little::klimt;

// ═══ Helper ═══════════════════════════════════════════════════════════

fn assert_close(name: &str, actual: f64, expected: f64) {
    assert!(
        (actual - expected).abs() < 1e-9,
        "{}: expected {}, got {}",
        name,
        expected,
        actual
    );
}

/// Allow small tolerance for font metrics (platform-dependent rounding)
fn assert_close_tol(name: &str, actual: f64, expected: f64, tol: f64) {
    assert!(
        (actual - expected).abs() <= tol,
        "{}: expected {} (±{}), got {} (diff={})",
        name,
        expected,
        tol,
        actual,
        (actual - expected).abs()
    );
}

// ═══ 1. Color resolution ══════════════════════════════════════════════

#[test]
fn color_named_matches_java() {
    let cases: &[(&str, &str)] = &[
        ("red", "#FF0000"),
        ("blue", "#0000FF"),
        ("green", "#008000"),
        ("yellow", "#FFFF00"),
        ("black", "#000000"),
        ("white", "#FFFFFF"),
        ("LightBlue", "#ADD8E6"),
        ("DarkSalmon", "#E9967A"),
        ("Gold", "#FFD700"),
        ("Navy", "#000080"),
        ("Crimson", "#DC143C"),
        ("Lavender", "#E6E6FA"),
        ("Aquamarine", "#7FFFD4"),
        ("Chocolate", "#D2691E"),
        ("Indigo", "#4B0082"),
        ("Lime", "#00FF00"),
        ("Olive", "#808000"),
        ("Teal", "#008080"),
    ];
    for &(name, expected) in cases {
        let color = klimt::color::resolve_color(name)
            .unwrap_or_else(|| panic!("color '{}' not resolved", name));
        assert_eq!(
            color.to_svg(),
            expected,
            "color '{}': expected {}, got {}",
            name,
            expected,
            color.to_svg()
        );
    }
}

#[test]
fn color_transparent_matches_java() {
    // Java returns "#00000000" for transparent
    let c = klimt::color::resolve_color("transparent").unwrap();
    assert!(
        c.is_none() || c.is_transparent(),
        "transparent should be none/transparent"
    );
}

#[test]
fn color_archimate_matches_java() {
    let cases: &[(&str, &str)] = &[
        ("APPLICATION", "#C2F0FF"),
        ("BUSINESS", "#FFFFCC"),
        ("TECHNOLOGY", "#C9FFC9"),
    ];
    for &(name, expected) in cases {
        let color = klimt::color::resolve_color(name)
            .unwrap_or_else(|| panic!("archimate color '{}' not resolved", name));
        assert_eq!(color.to_svg(), expected, "archimate '{}'", name);
    }
}

// ═══ 2. HColor methods ════════════════════════════════════════════════

#[test]
fn color_is_dark_matches_java() {
    use klimt::color::HColor;
    // Java: black is dark, white is not, red is dark
    assert!(HColor::rgb(0, 0, 0).is_dark(), "black should be dark");
    assert!(
        !HColor::rgb(255, 255, 255).is_dark(),
        "white should not be dark"
    );
    assert!(HColor::rgb(255, 0, 0).is_dark(), "red should be dark");
}

// ═══ 3. UStroke ════════════════════════════════════════════════════════

#[test]
fn ustroke_matches_java() {
    let dashed = klimt::UStroke::new(5.0, 5.0, 1.0);
    assert_close("dash_vis", dashed.dash_visible, 5.0);
    assert_close("dash_spc", dashed.dash_space, 5.0);
    assert_close("dash_thick", dashed.thickness, 1.0);
    let da = dashed.dasharray_svg().unwrap();
    assert_close("dasharray_0", da.0, 5.0);
    assert_close("dasharray_1", da.1, 5.0);

    let solid = klimt::UStroke::with_thickness(1.5);
    assert!(solid.dasharray_svg().is_none(), "solid should have no dash");
    assert_close("solid_thick", solid.thickness, 1.5);

    let simple = klimt::UStroke::simple();
    assert_close("simple_thick", simple.thickness, 1.0);
}

// ═══ 4. UTranslate ════════════════════════════════════════════════════

#[test]
fn utranslate_matches_java() {
    let t1 = klimt::UTranslate::new(10.0, 20.0);
    let t2 = klimt::UTranslate::new(5.0, -3.0);

    let t3 = t1.compose(t2);
    assert_close("compose_dx", t3.dx, 15.0);
    assert_close("compose_dy", t3.dy, 17.0);

    let t4 = t1.reverse();
    assert_close("reverse_dx", t4.dx, -10.0);
    assert_close("reverse_dy", t4.dy, -20.0);

    let t5 = t1.scaled(2.0);
    assert_close("scaled_dx", t5.dx, 20.0);
    assert_close("scaled_dy", t5.dy, 40.0);
}

// ═══ 5. XPoint2D ══════════════════════════════════════════════════════

#[test]
fn xpoint2d_matches_java() {
    use klimt::geom::XPoint2D;
    assert_close(
        "dist_3_4",
        XPoint2D::distance_between(0.0, 0.0, 3.0, 4.0),
        5.0,
    );
    let p1 = XPoint2D::new(10.0, 20.0);
    let p2 = XPoint2D::new(13.0, 24.0);
    assert_close("dist_p1_p2", p1.distance(&p2), 5.0);
}

// ═══ 6. XDimension2D ══════════════════════════════════════════════════

#[test]
fn xdimension2d_matches_java() {
    use klimt::geom::XDimension2D;
    let d1 = XDimension2D::new(100.0, 50.0);
    let d2 = XDimension2D::new(80.0, 30.0);

    let tb = d1.merge_vertical(&d2);
    assert_close("tb_w", tb.width, 100.0);
    assert_close("tb_h", tb.height, 80.0);

    let lr = d1.merge_horizontal(&d2);
    assert_close("lr_w", lr.width, 180.0);
    assert_close("lr_h", lr.height, 50.0);

    let mx = d1.max(&d2);
    assert_close("max_w", mx.width, 100.0);
    assert_close("max_h", mx.height, 50.0);

    let dl = d1.delta(10.0, -5.0);
    assert_close("delta_w", dl.width, 110.0);
    assert_close("delta_h", dl.height, 45.0);
}

// ═══ 7. XLine2D ═══════════════════════════════════════════════════════

#[test]
fn xline2d_matches_java() {
    use klimt::geom::{XLine2D, XPoint2D};
    let line = XLine2D::from_points(XPoint2D::new(0.0, 0.0), XPoint2D::new(10.0, 0.0));
    let mid = line.middle();
    assert_close("mid_x", mid.x, 5.0);
    assert_close("mid_y", mid.y, 0.0);
    assert_close("angle_horiz", line.angle(), 0.0);

    let line2 = XLine2D::from_points(XPoint2D::new(0.0, 0.0), XPoint2D::new(0.0, 10.0));
    assert_close("angle_vert", line2.angle(), std::f64::consts::FRAC_PI_2);
}

// ═══ 8. URectangle ════════════════════════════════════════════════════

#[test]
fn urectangle_matches_java() {
    use klimt::shape::URectangle;
    let rect = URectangle::build(100.0, 50.0);
    assert_close("rect_w", rect.width, 100.0);
    assert_close("rect_h", rect.height, 50.0);

    let rr = rect.rounded(10.0);
    assert_close("rect_rx", rr.rx, 10.0);
    assert_close("rect_ry", rr.ry, 10.0);
}

// ═══ 9. UEllipse ══════════════════════════════════════════════════════

#[test]
fn uellipse_matches_java() {
    use klimt::shape::UEllipse;
    let ell = UEllipse::build(80.0, 60.0);
    assert_close("ell_w", ell.width, 80.0);
    assert_close("ell_h", ell.height, 60.0);

    // Point at angle 0: rightmost
    let ep = ell.point_at_angle(0.0);
    assert_close("ell_pt0_x", ep.x, 80.0);
    assert_close("ell_pt0_y", ep.y, 30.0);

    // Point at angle PI: leftmost
    let ep2 = ell.point_at_angle(std::f64::consts::PI);
    assert!(ep2.x.abs() < 1e-9, "ell_ptPI_x should be ~0, got {}", ep2.x);
    assert_close("ell_ptPI_y", ep2.y, 30.0);
}

// ═══ 10. ULine ════════════════════════════════════════════════════════

#[test]
fn uline_matches_java() {
    use klimt::shape::ULine;
    let h = ULine::hline(100.0);
    assert_close("uline_h_dx", h.dx, 100.0);
    assert_close("uline_h_dy", h.dy, 0.0);

    let v = ULine::vline(50.0);
    assert_close("uline_v_dx", v.dx, 0.0);
    assert_close("uline_v_dy", v.dy, 50.0);
}

// ═══ 11. Number formatting (CRITICAL for SVG matching) ════════════════

#[test]
fn number_format_matches_java() {
    use klimt::svg::test_helpers::fmt_at_scale_1;

    let cases: &[(f64, &str)] = &[
        (0.0, "0"),
        (42.0, "42"),
        (1.5, "1.5"),
        (1.23456, "1.2346"),
        // Java returns "-0" for -0.00004; we allow "0" or "-0"
        (30.2969, "30.2969"),
        (47.667, "47.667"),
        (0.5, "0.5"),
        (24.9951, "24.9951"),
        (33.667, "33.667"),
        (114.5625, "114.5625"),
        (36.2969, "36.2969"),
        (167.6152, "167.6152"),
        (5.0, "5"),
        (2.5, "2.5"),
        (13.9688, "13.9688"),
        (7.0, "7"),
        (1.0, "1"),
    ];
    for &(value, expected) in cases {
        let actual = fmt_at_scale_1(value);
        assert_eq!(
            actual, expected,
            "fmt({}): expected '{}', got '{}'",
            value, expected, actual
        );
    }
}

// ═══ 12. SVG element attribute order verification ═════════════════════

#[test]
fn svg_rect_attribute_order_matches_java() {
    use klimt::svg::SvgGraphic;
    let mut svg = SvgGraphic::new(12345, 1.0);
    svg.set_fill_color("#E2E2F0");
    svg.set_stroke_color(Some("#181818"));
    svg.set_stroke_width(0.5, None);
    svg.svg_rectangle(5.0, 5.0, 47.667, 30.2969, 2.5, 2.5, 0.0);
    let body = svg.body();

    // Verify exact Java DOM alphabetical attribute order: fill < height < rx < ry < style < width < x < y
    let fill_pos = body.find("fill=").expect("fill");
    let height_pos = body.find("height=").expect("height");
    let rx_pos = body.find("rx=").expect("rx");
    let style_pos = body.find("style=").expect("style");
    let width_pos = body.find("width=").expect("width");
    let x_pos = body.find(" x=").expect("x");
    let y_pos = body.find(" y=").expect("y");
    assert!(fill_pos < height_pos, "fill < height");
    assert!(height_pos < rx_pos, "height < rx");
    assert!(rx_pos < style_pos, "rx < style");
    assert!(style_pos < width_pos, "style < width");
    assert!(width_pos < x_pos, "width < x");
    assert!(x_pos < y_pos, "x < y");
}

#[test]
fn svg_text_attribute_order_matches_java() {
    use klimt::svg::{LengthAdjust, SvgGraphic};
    let mut svg = SvgGraphic::new(12345, 1.0);
    svg.set_fill_color("#000000");
    svg.svg_text(
        "Alice",
        12.0,
        24.9951,
        Some("sans-serif"),
        14.0,
        None,
        None,
        None,
        33.667,
        LengthAdjust::Spacing,
        None,
        0,
        None,
    );
    let body = svg.body();

    // Java reference: fill, font-family, font-size, lengthAdjust, textLength, x, y
    assert!(body.contains("fill="), "has fill");
    assert!(
        body.contains("font-family=\"sans-serif\""),
        "has font-family"
    );
    assert!(body.contains("font-size=\"14\""), "has font-size");
    assert!(
        body.contains("lengthAdjust=\"spacing\""),
        "has lengthAdjust"
    );
    assert!(body.contains("textLength=\"33.667\""), "has textLength");
    assert!(body.contains(">Alice</text>"), "has text content");
}

// ═══ 13. SVG root element matches Java format ═════════════════════════

#[test]
fn svg_root_element_matches_java_format() {
    use klimt::svg::SvgGraphic;
    let mut svg = SvgGraphic::new(12345, 1.0);
    svg.set_max(115, 122);
    let doc = svg.to_svg(Some("#FFFFFF"), "SEQUENCE");

    // Compare with Java's exact output from diag0_root.
    // The output starts with a <?plantuml ...?> processing instruction,
    // followed by the <svg> root element.
    let expected_fragment = r#"<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" contentStyleType="text/css" data-diagram-type="SEQUENCE""#;
    assert!(
        doc.contains(expected_fragment),
        "SVG root should contain:\n{}\nbut got:\n{}",
        expected_fragment,
        &doc[..doc.len().min(200)]
    );

    // Check key attributes present
    assert!(doc.contains("height=\"122px\""), "height");
    assert!(
        doc.contains("preserveAspectRatio=\"none\""),
        "preserveAspectRatio"
    );
    assert!(
        doc.contains(r##"style="width:115px;height:122px;background:#FFFFFF;""##),
        "style"
    );
    assert!(doc.contains("version=\"1.1\""), "version");
    assert!(doc.contains("viewBox=\"0 0 115 122\""), "viewBox");
    assert!(doc.contains("width=\"115px\""), "width");
    assert!(doc.contains("zoomAndPan=\"magnify\">"), "zoomAndPan");
}

// ═══ 14. Font metrics (StringBounder) - CRITICAL ═════════════════════

#[test]
fn font_metrics_text_width_sansserif14() {
    use plantuml_little::font_metrics::text_width;
    // Java: SansSerif 14 plain
    // "Alice" = 32.0, "Bob" = 28.0
    // Note: pre-computed tables may differ from this machine's Java AWT by ~2px
    assert_close_tol(
        "Alice_w",
        text_width("Alice", "SansSerif", 14.0, false, false),
        32.0,
        2.0,
    );
    assert_close_tol(
        "Bob_w",
        text_width("Bob", "SansSerif", 14.0, false, false),
        28.0,
        2.0,
    );
}

#[test]
fn font_metrics_text_width_sansserif13() {
    use plantuml_little::font_metrics::text_width;
    // Java: SansSerif 13 plain, "hello" = 30.0
    assert_close_tol(
        "hello_w",
        text_width("hello", "SansSerif", 13.0, false, false),
        30.0,
        2.0,
    );
}

#[test]
fn font_metrics_text_width_mono13() {
    use plantuml_little::font_metrics::text_width;
    // Java: Monospaced 13 plain, "code" = 32.0
    assert_close_tol(
        "code_w",
        text_width("code", "Monospaced", 13.0, false, false),
        32.0,
        1.0,
    );
}

#[test]
fn font_metrics_text_width_sansserif12() {
    use plantuml_little::font_metrics::text_width;
    // Java: SansSerif 12 plain, "A much longer text" = 118.0
    assert_close_tol(
        "long_w",
        text_width("A much longer text", "SansSerif", 12.0, false, false),
        118.0,
        4.0,
    );
}

#[test]
fn font_metrics_text_width_bold() {
    use plantuml_little::font_metrics::text_width;
    // Java: SansSerif 14 bold
    // "Alice" = 38.0, "Bob" = 30.0
    assert_close_tol(
        "bold_Alice_w",
        text_width("Alice", "SansSerif", 14.0, true, false),
        38.0,
        1.0,
    );
    assert_close_tol(
        "bold_Bob_w",
        text_width("Bob", "SansSerif", 14.0, true, false),
        30.0,
        1.0,
    );
}

#[test]
fn font_metrics_text_width_bold_sansserif13() {
    use plantuml_little::font_metrics::text_width;
    // Java: SansSerif 13 bold, "hello" = 35.0
    assert_close_tol(
        "bold_hello_w",
        text_width("hello", "SansSerif", 13.0, true, false),
        35.0,
        1.0,
    );
}

#[test]
fn font_metrics_text_width_bold_mono13() {
    use plantuml_little::font_metrics::text_width;
    // Java: Monospaced 13 bold, "code" = 32.0
    assert_close_tol(
        "bold_code_w",
        text_width("code", "Monospaced", 13.0, true, false),
        32.0,
        1.0,
    );
}

#[test]
fn font_metrics_single_chars_sansserif14() {
    use plantuml_little::font_metrics::text_width;
    // Java: SansSerif 14 plain
    // " " = 4.0, "M" = 12.0, "W" = 13.0, "i" = 3.0
    assert_close_tol(
        "space_w",
        text_width(" ", "SansSerif", 14.0, false, false),
        4.0,
        1.0,
    );
    assert_close_tol(
        "M_w",
        text_width("M", "SansSerif", 14.0, false, false),
        12.0,
        1.0,
    );
    assert_close_tol(
        "W_w",
        text_width("W", "SansSerif", 14.0, false, false),
        13.0,
        1.0,
    );
    assert_close_tol(
        "i_w",
        text_width("i", "SansSerif", 14.0, false, false),
        3.0,
        1.0,
    );
}

#[test]
fn font_metrics_digit_string_sansserif14() {
    use plantuml_little::font_metrics::text_width;
    // Java: SansSerif 14 plain, "0123456789" = 90.0
    assert_close_tol(
        "digit_w",
        text_width("0123456789", "SansSerif", 14.0, false, false),
        90.0,
        2.0,
    );
}

#[test]
fn font_metrics_digit_string_mono14() {
    use plantuml_little::font_metrics::text_width;
    // Java: Monospaced 14 plain, "0123456789" = 80.0 (8px per char)
    // Note: pre-computed width tables may differ from this machine's AWT by ~5px
    assert_close_tol(
        "mono_digit_w",
        text_width("0123456789", "Monospaced", 14.0, false, false),
        80.0,
        5.0,
    );
}

#[test]
fn font_metrics_italic_sansserif14() {
    use plantuml_little::font_metrics::text_width;
    // Java: SansSerif 14 italic, "Alice" = 32.0
    assert_close_tol(
        "italic_Alice_w",
        text_width("Alice", "SansSerif", 14.0, false, true),
        32.0,
        2.0,
    );
}

#[test]
fn font_metrics_italic_mono13() {
    use plantuml_little::font_metrics::text_width;
    // Java: Monospaced 13 italic, "code" = 32.0
    assert_close_tol(
        "italic_code_w",
        text_width("code", "Monospaced", 13.0, false, true),
        32.0,
        1.0,
    );
}

// ═══ 15. Font vertical metrics ═══════════════════════════════════════

#[test]
fn font_metrics_line_height() {
    use plantuml_little::font_metrics::line_height;
    // Java vertical metrics: line height = ascent + descent + leading
    // Java getHeight() returns integer-rounded values; our tables use fractional.
    // SansSerif 14: Java height = 17.0, our tables have fractional (16.297 or similar)
    assert_close_tol(
        "sansserif14_h",
        line_height("SansSerif", 14.0, false, false),
        17.0,
        2.0,
    );
    // SansSerif 13: Java height = 17.0
    assert_close_tol(
        "sansserif13_h",
        line_height("SansSerif", 13.0, false, false),
        17.0,
        2.0,
    );
    // SansSerif 12: Java height = 15.0
    assert_close_tol(
        "sansserif12_h",
        line_height("SansSerif", 12.0, false, false),
        15.0,
        2.0,
    );
    // Monospaced 13: Java height = 17.0
    assert_close_tol(
        "mono13_h",
        line_height("Monospaced", 13.0, false, false),
        17.0,
        2.0,
    );
    // Monospaced 14: Java height = 17.0
    assert_close_tol(
        "mono14_h",
        line_height("Monospaced", 14.0, false, false),
        17.0,
        2.0,
    );
}

#[test]
fn font_metrics_line_height_bold() {
    use plantuml_little::font_metrics::line_height;
    // SansSerif 14 bold: Java height = 17.0
    assert_close_tol(
        "sansserif14b_h",
        line_height("SansSerif", 14.0, true, false),
        17.0,
        2.0,
    );
    // SansSerif 13 bold: Java height = 17.0
    assert_close_tol(
        "sansserif13b_h",
        line_height("SansSerif", 13.0, true, false),
        17.0,
        2.0,
    );
    // Monospaced 13 bold: Java height = 17.0
    assert_close_tol(
        "mono13b_h",
        line_height("Monospaced", 13.0, true, false),
        17.0,
        2.0,
    );
}

#[test]
fn font_metrics_ascent() {
    use plantuml_little::font_metrics::ascent;
    // Java: SansSerif 14 ascent = 13.0
    assert_close_tol(
        "sansserif14_asc",
        ascent("SansSerif", 14.0, false, false),
        13.0,
        1.0,
    );
    // Java: SansSerif 12 ascent = 12.0
    assert_close_tol(
        "sansserif12_asc",
        ascent("SansSerif", 12.0, false, false),
        12.0,
        1.0,
    );
    // Java: Monospaced 13 ascent = 13.0
    assert_close_tol(
        "mono13_asc",
        ascent("Monospaced", 13.0, false, false),
        13.0,
        1.0,
    );
}

#[test]
fn font_metrics_descent() {
    use plantuml_little::font_metrics::descent;
    // Java: SansSerif 14 descent = 4.0
    assert_close_tol(
        "sansserif14_desc",
        descent("SansSerif", 14.0, false, false),
        4.0,
        1.0,
    );
    // Java: SansSerif 12 descent = 3.0
    assert_close_tol(
        "sansserif12_desc",
        descent("SansSerif", 12.0, false, false),
        3.0,
        1.0,
    );
    // Java: Monospaced 13 descent = 4.0
    assert_close_tol(
        "mono13_desc",
        descent("Monospaced", 13.0, false, false),
        4.0,
        1.0,
    );
}

// ═══ 16. Color darken/lighten HSL ════════════════════════════════════

#[test]
fn color_darken_hsl_matches_java() {
    use klimt::color::HColor;
    // Red (#FF0000) darken 20% -> #CC0000
    let red = HColor::rgb(255, 0, 0);
    let darkened = red.darken_hsl(20);
    assert_eq!(darkened.to_svg(), "#CC0000", "red darken 20%");

    // Blue (#0000FF) darken 30% -> #0000B3
    let blue = HColor::rgb(0, 0, 255);
    let bd = blue.darken_hsl(30);
    assert_eq!(bd.to_svg(), "#0000B3", "blue darken 30%");

    // Gold (#FFD700) darken 10% -> #E6C100
    let gold = HColor::rgb(255, 215, 0);
    let gd = gold.darken_hsl(10);
    assert_eq!(gd.to_svg(), "#E6C100", "gold darken 10%");

    // Gray (#808080) darken 25% -> #606060
    let gray = HColor::rgb(128, 128, 128);
    let grd = gray.darken_hsl(25);
    assert_eq!(grd.to_svg(), "#606060", "gray darken 25%");
}

#[test]
fn color_lighten_hsl_matches_java() {
    use klimt::color::HColor;
    // Red (#FF0000) lighten 20% -> #FF3333
    let red = HColor::rgb(255, 0, 0);
    let lightened = red.lighten_hsl(20);
    assert_eq!(lightened.to_svg(), "#FF3333", "red lighten 20%");

    // Blue (#0000FF) lighten 30% -> #4C4CFF
    let blue = HColor::rgb(0, 0, 255);
    let bl = blue.lighten_hsl(30);
    assert_eq!(bl.to_svg(), "#4C4CFF", "blue lighten 30%");

    // Gold (#FFD700) lighten 10% -> #FFDB1A
    let gold = HColor::rgb(255, 215, 0);
    let gl = gold.lighten_hsl(10);
    assert_eq!(gl.to_svg(), "#FFDB1A", "gold lighten 10%");

    // Gray (#808080) lighten 25% -> #A0A0A0
    let gray = HColor::rgb(128, 128, 128);
    let grl = gray.lighten_hsl(25);
    assert_eq!(grl.to_svg(), "#A0A0A0", "gray lighten 25%");
}

// ═══ 17. SVG element fragment verification ═══════════════════════════

#[test]
fn svg_rect_fragment_matches_java() {
    use klimt::svg::SvgGraphic;
    // Java first rect in sequence diagram:
    // <rect fill="#E2E2F0" height="30.2969" rx="2.5" ry="2.5"
    //   style="stroke:#181818;stroke-width:0.5;" width="47.667" x="5" y="5"/>
    let mut svg = SvgGraphic::new(12345, 1.0);
    svg.set_fill_color("#E2E2F0");
    svg.set_stroke_color(Some("#181818"));
    svg.set_stroke_width(0.5, None);
    svg.svg_rectangle(5.0, 5.0, 47.667, 30.2969, 2.5, 2.5, 0.0);
    let body = svg.body();

    // Verify exact attribute values
    assert!(body.contains(r##"fill="#E2E2F0""##), "fill value: {}", body);
    assert!(
        body.contains("height=\"30.2969\""),
        "height value: {}",
        body
    );
    assert!(body.contains("rx=\"2.5\""), "rx value: {}", body);
    assert!(body.contains("ry=\"2.5\""), "ry value: {}", body);
    assert!(
        body.contains("stroke:#181818;stroke-width:0.5;"),
        "style value: {}",
        body
    );
    assert!(body.contains("width=\"47.667\""), "width value: {}", body);
    assert!(body.contains(" x=\"5\""), "x value: {}", body);
    assert!(body.contains(" y=\"5\""), "y value: {}", body);
}

#[test]
fn svg_ellipse_fragment_matches_java() {
    use klimt::svg::SvgGraphic;
    let mut svg = SvgGraphic::new(12345, 1.0);
    svg.set_fill_color("#FEFECE");
    svg.set_stroke_color(Some("#A80036"));
    svg.set_stroke_width(1.5, None);
    svg.svg_ellipse(50.0, 30.0, 11.0, 11.0, 0.0);
    let body = svg.body();

    assert!(body.contains("cx=\"50\""), "cx value: {}", body);
    assert!(body.contains("cy=\"30\""), "cy value: {}", body);
    assert!(body.contains("rx=\"11\""), "rx value: {}", body);
    assert!(body.contains("ry=\"11\""), "ry value: {}", body);
    assert!(body.contains(r##"fill="#FEFECE""##), "fill value: {}", body);
    assert!(body.contains("stroke:#A80036"), "stroke color: {}", body);
    assert!(body.contains("stroke-width:1.5"), "stroke width: {}", body);
}

#[test]
fn svg_line_fragment_matches_java() {
    use klimt::svg::SvgGraphic;
    // Java first line: dashed line for lifeline
    let mut svg = SvgGraphic::new(12345, 1.0);
    svg.set_stroke_color(Some("#181818"));
    svg.set_stroke_width(0.5, Some((5.0, 5.0)));
    svg.svg_line(28.0, 36.2969, 28.0, 85.4297, 0.0);
    let body = svg.body();

    assert!(body.contains("x1=\"28\""), "x1: {}", body);
    assert!(body.contains("x2=\"28\""), "x2: {}", body);
    assert!(body.contains("y1=\"36.2969\""), "y1: {}", body);
    assert!(body.contains("y2=\"85.4297\""), "y2: {}", body);
    assert!(body.contains("stroke:#181818"), "stroke: {}", body);
    assert!(body.contains("stroke-width:0.5"), "stroke-width: {}", body);
    assert!(body.contains("stroke-dasharray:5,5"), "dasharray: {}", body);
}

#[test]
fn svg_polygon_fragment_matches_java() {
    use klimt::svg::SvgGraphic;
    // Java: polygon for arrow
    // points="72.248,63.4297,82.248,67.4297,72.248,71.4297,76.248,67.4297"
    let mut svg = SvgGraphic::new(12345, 1.0);
    svg.set_fill_color("#181818");
    svg.set_stroke_color(Some("#181818"));
    svg.set_stroke_width(1.0, None);
    svg.svg_polygon(
        0.0,
        &[
            72.248, 63.4297, 82.248, 67.4297, 72.248, 71.4297, 76.248, 67.4297,
        ],
    );
    let body = svg.body();

    assert!(body.contains(r##"fill="#181818""##), "fill: {}", body);
    assert!(
        body.contains("points=\"72.248,63.4297,82.248,67.4297,72.248,71.4297,76.248,67.4297\""),
        "points: {}",
        body
    );
    assert!(body.contains("stroke:#181818"), "stroke: {}", body);
    assert!(body.contains("stroke-width:1"), "stroke-width: {}", body);
}

#[test]
fn svg_text_fragment_matches_java() {
    use klimt::svg::{LengthAdjust, SvgGraphic};
    // Java first text:
    // <text fill="#000000" font-family="sans-serif" font-size="14"
    //   lengthAdjust="spacing" textLength="33.667" x="12" y="24.9951">Alice</text>
    let mut svg = SvgGraphic::new(12345, 1.0);
    svg.set_fill_color("#000000");
    svg.svg_text(
        "Alice",
        12.0,
        24.9951,
        Some("sans-serif"),
        14.0,
        None,
        None,
        None,
        33.667,
        LengthAdjust::Spacing,
        None,
        0,
        None,
    );
    let body = svg.body();

    assert!(body.contains(r##"fill="#000000""##), "fill: {}", body);
    assert!(
        body.contains("font-family=\"sans-serif\""),
        "font-family: {}",
        body
    );
    assert!(body.contains("font-size=\"14\""), "font-size: {}", body);
    assert!(
        body.contains("lengthAdjust=\"spacing\""),
        "lengthAdjust: {}",
        body
    );
    assert!(
        body.contains("textLength=\"33.667\""),
        "textLength: {}",
        body
    );
    assert!(body.contains(" x=\"12\""), "x: {}", body);
    assert!(body.contains(" y=\"24.9951\""), "y: {}", body);
    assert!(body.contains(">Alice</text>"), "text content: {}", body);
}

// ═══ 18. Shadow filter fragment ═══════════════════════════════════════

#[test]
fn svg_shadow_filter_structure_matches_java() {
    use klimt::svg::SvgGraphic;
    // Trigger shadow filter creation by drawing a rect with shadow
    let mut svg = SvgGraphic::new(12345, 1.0);
    svg.set_fill_color("#E2E2F0");
    svg.set_stroke_color(Some("#181818"));
    svg.set_stroke_width(0.5, None);
    svg.svg_rectangle(5.0, 5.0, 100.0, 50.0, 0.0, 0.0, 3.0); // deltaShadow=3
    let defs = svg.defs();

    // Verify shadow filter elements match Java structure
    assert!(defs.contains("<filter"), "has filter element");
    assert!(
        defs.contains("height=\"300%\""),
        "filter height=300%: {}",
        defs
    );
    assert!(
        defs.contains("width=\"300%\""),
        "filter width=300%: {}",
        defs
    );
    assert!(defs.contains("x=\"-1\""), "filter x=-1: {}", defs);
    assert!(defs.contains("y=\"-1\""), "filter y=-1: {}", defs);
    assert!(
        defs.contains("feGaussianBlur"),
        "has feGaussianBlur: {}",
        defs
    );
    assert!(
        defs.contains("stdDeviation=\"2\""),
        "stdDeviation=2: {}",
        defs
    );
    assert!(
        defs.contains("feColorMatrix"),
        "has feColorMatrix: {}",
        defs
    );
    assert!(
        defs.contains("0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 .4 0"),
        "color matrix values: {}",
        defs
    );
    assert!(defs.contains("feOffset"), "has feOffset: {}", defs);
    assert!(defs.contains("dx=\"4\""), "feOffset dx=4: {}", defs);
    assert!(defs.contains("dy=\"4\""), "feOffset dy=4: {}", defs);
    assert!(defs.contains("feBlend"), "has feBlend: {}", defs);
    assert!(
        defs.contains("in=\"SourceGraphic\""),
        "feBlend in=SourceGraphic: {}",
        defs
    );
    assert!(
        defs.contains("mode=\"normal\""),
        "feBlend mode=normal: {}",
        defs
    );
}

// ═══ 19. Gradient creation ═══════════════════════════════════════════

#[test]
fn svg_gradient_policies_match_java() {
    use klimt::svg::SvgGraphic;

    // Policy '|' (horizontal): x1=0% y1=50% x2=100% y2=50%
    let mut svg = SvgGraphic::new(12345, 1.0);
    let id = svg.create_svg_gradient("#FF0000", "#0000FF", '|');
    let defs = svg.defs();
    assert!(defs.contains("x1=\"0%\""), "pipe x1: {}", defs);
    assert!(defs.contains("y1=\"50%\""), "pipe y1: {}", defs);
    assert!(defs.contains("x2=\"100%\""), "pipe x2: {}", defs);
    assert!(defs.contains("y2=\"50%\""), "pipe y2: {}", defs);
    assert!(
        defs.contains(r##"stop-color="#FF0000""##),
        "stop1 color: {}",
        defs
    );
    assert!(
        defs.contains(r##"stop-color="#0000FF""##),
        "stop2 color: {}",
        defs
    );
    assert!(!id.is_empty(), "gradient id not empty");

    // Policy '-' (vertical): x1=50% y1=0% x2=50% y2=100%
    let mut svg2 = SvgGraphic::new(12345, 1.0);
    svg2.create_svg_gradient("#FF0000", "#0000FF", '-');
    let defs2 = svg2.defs();
    assert!(defs2.contains("x1=\"50%\""), "dash x1: {}", defs2);
    assert!(defs2.contains("y1=\"0%\""), "dash y1: {}", defs2);
    assert!(defs2.contains("x2=\"50%\""), "dash x2: {}", defs2);
    assert!(defs2.contains("y2=\"100%\""), "dash y2: {}", defs2);

    // Policy '\\' (anti-diagonal): x1=0% y1=100% x2=100% y2=0%
    let mut svg3 = SvgGraphic::new(12345, 1.0);
    svg3.create_svg_gradient("#FF0000", "#0000FF", '\\');
    let defs3 = svg3.defs();
    assert!(defs3.contains("x1=\"0%\""), "backslash x1: {}", defs3);
    assert!(defs3.contains("y1=\"100%\""), "backslash y1: {}", defs3);
    assert!(defs3.contains("x2=\"100%\""), "backslash x2: {}", defs3);
    assert!(defs3.contains("y2=\"0%\""), "backslash y2: {}", defs3);

    // Policy '/' (diagonal, default): x1=0% y1=0% x2=100% y2=100%
    let mut svg4 = SvgGraphic::new(12345, 1.0);
    svg4.create_svg_gradient("#FF0000", "#0000FF", '/');
    let defs4 = svg4.defs();
    assert!(defs4.contains("x1=\"0%\""), "slash x1: {}", defs4);
    assert!(defs4.contains("y1=\"0%\""), "slash y1: {}", defs4);
    assert!(defs4.contains("x2=\"100%\""), "slash x2: {}", defs4);
    assert!(defs4.contains("y2=\"100%\""), "slash y2: {}", defs4);
}

#[test]
fn svg_gradient_dedup_matches_java() {
    use klimt::svg::SvgGraphic;
    // Same parameters should return same ID (deduplication)
    let mut svg = SvgGraphic::new(12345, 1.0);
    let id1 = svg.create_svg_gradient("#FF0000", "#0000FF", '/');
    let id2 = svg.create_svg_gradient("#FF0000", "#0000FF", '/');
    assert_eq!(id1, id2, "same gradient params should return same ID");

    // Different policy should return different ID
    let id3 = svg.create_svg_gradient("#FF0000", "#0000FF", '|');
    assert_ne!(id1, id3, "different policy should return different ID");
}

// ═══ 20. UPath SVG output ════════════════════════════════════════════

#[test]
fn upath_svg_rect_d_attribute() {
    use klimt::shape::UPath;
    use klimt::svg::SvgGraphic;
    // Build a rectangle path and render via SvgGraphic at offset (5, 3)
    let mut path = UPath::new();
    path.move_to(10.0, 20.0);
    path.line_to(50.0, 20.0);
    path.line_to(50.0, 60.0);
    path.line_to(10.0, 60.0);

    let mut svg = SvgGraphic::new(12345, 1.0);
    svg.set_fill_color("#FFFFFF");
    svg.set_stroke_color(Some("#000000"));
    svg.set_stroke_width(1.0, None);
    svg.svg_path(5.0, 3.0, &path, 0.0);
    let body = svg.body();

    // Java expected: "M15,23 L55,23 L55,63 L15,63"
    assert!(
        body.contains("d=\"M15,23 L55,23 L55,63 L15,63\""),
        "rect path d attribute: {}",
        body
    );
}

#[test]
fn upath_svg_cubic_d_attribute() {
    use klimt::shape::UPath;
    use klimt::svg::SvgGraphic;
    // Build a cubic path and render at offset (0, 0)
    let mut path = UPath::new();
    path.move_to(0.0, 0.0);
    path.cubic_to(10.0, 0.0, 20.0, 10.0, 20.0, 20.0);

    let mut svg = SvgGraphic::new(12345, 1.0);
    svg.set_fill_color("#FFFFFF");
    svg.set_stroke_color(Some("#000000"));
    svg.set_stroke_width(1.0, None);
    svg.svg_path(0.0, 0.0, &path, 0.0);
    let body = svg.body();

    // Java expected: "M0,0 C10,0 20,10 20,20"
    assert!(
        body.contains("d=\"M0,0 C10,0 20,10 20,20\""),
        "cubic path d attribute: {}",
        body
    );
}

#[test]
fn upath_svg_arc_d_attribute() {
    use klimt::shape::UPath;
    use klimt::svg::SvgGraphic;
    // Build an arc path and render at offset (10, 5)
    let mut path = UPath::new();
    path.move_to(0.0, 0.0);
    path.arc_to(25.0, 25.0, 0.0, 0.0, 1.0, 50.0, 25.0);

    let mut svg = SvgGraphic::new(12345, 1.0);
    svg.set_fill_color("#FFFFFF");
    svg.set_stroke_color(Some("#000000"));
    svg.set_stroke_width(1.0, None);
    svg.svg_path(10.0, 5.0, &path, 0.0);
    let body = svg.body();

    // Java expected: "M10,5 A25,25 0 0 1 60,30"
    assert!(
        body.contains("d=\"M10,5 A25,25 0 0 1 60,30\""),
        "arc path d attribute: {}",
        body
    );
}

// ═══ 21. SVG line with solid stroke ══════════════════════════════════

#[test]
fn svg_line_solid_matches_java() {
    use klimt::svg::SvgGraphic;
    // Solid line (like arrow shaft)
    let mut svg = SvgGraphic::new(12345, 1.0);
    svg.set_stroke_color(Some("#181818"));
    svg.set_stroke_width(1.0, None);
    svg.svg_line(28.8335, 67.4297, 78.248, 67.4297, 0.0);
    let body = svg.body();

    assert!(body.contains("x1=\"28.8335\""), "x1: {}", body);
    assert!(body.contains("y1=\"67.4297\""), "y1: {}", body);
    assert!(body.contains("x2=\"78.248\""), "x2: {}", body);
    assert!(body.contains("y2=\"67.4297\""), "y2: {}", body);
    assert!(body.contains("stroke:#181818"), "stroke: {}", body);
    assert!(body.contains("stroke-width:1"), "stroke-width: {}", body);
    // No dasharray for solid line
    assert!(!body.contains("stroke-dasharray"), "no dasharray: {}", body);
}

// ═══ 22. Fill opacity for transparent colors ═════════════════════════

#[test]
fn svg_fill_opacity_matches_java() {
    use klimt::svg::SvgGraphic;
    // Java: fill="#000000" fill-opacity="0.00000" for transparent black
    // Uses WITH_FILL_OPACITY path (set_fill_color_with_opacity)
    let mut svg = SvgGraphic::new(12345, 1.0);
    svg.set_fill_color_with_opacity("#00000000");
    svg.set_stroke_color(None);
    svg.set_stroke_width(0.0, None);
    svg.svg_rectangle(24.0, 36.0, 8.0, 49.0, 0.0, 0.0, 0.0);
    let body = svg.body();

    // When fill has 8 hex digits, Java splits into fill + fill-opacity
    assert!(
        body.contains(r##"fill="#000000""##),
        "fill without alpha: {}",
        body
    );
    assert!(body.contains("fill-opacity="), "has fill-opacity: {}", body);
}

// ═══ 23. Font calculateDimension height matches Java ═════════════════

#[test]
fn font_dimension_height_matches_java() {
    use plantuml_little::font_metrics::line_height;
    // Java StringBounder.calculateDimension returns height from Rectangle2D
    // SansSerif 14 "Alice" h=16.296875 = ascent + descent in points
    // Our line_height returns ascent+descent+leading
    // The actual text bounding box height from Java is 16.296875
    // But line_height (integer metrics) = 17.0
    // The difference is because Java uses fractional metrics for StringBounds
    // but integer metrics for getHeight()
    // Our system should use line_height() for layout (matches Java getHeight())
    let h = line_height("SansSerif", 14.0, false, false);
    assert_close_tol("sansserif14_layout_h", h, 17.0, 1.0);
}
